# Generated by Django 4.2.30 on 2026-05-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SolverRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip", models.CharField(max_length=64)),
                ("expression_type", models.CharField(max_length=32)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="app_solverr_timesta_77cc7c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatbotRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip", models.CharField(max_length=64)),
                ("calculus_related", models.BooleanField(default=True)),
                ("had_steps", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="app_chatbot_timesta_6b46c4_idx"
                    )
                ],
            },
        ),
    ]
